M48
; DRILL file {KiCad 7.0.9} date Fri 24 Nov 2023 12:14:20 AM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-24T00:14:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X5.8941Y-5.5892
X6.085Y-5.5892
T2
X5.8823Y-5.7085
X6.0969Y-5.7085
T3
X4.3Y-2.2713
X4.3Y-5.15
X7.6378Y-2.2713
X7.6378Y-5.15
T0
M30
