M48
; DRILL file {KiCad 7.0.9} date Wed 29 Nov 2023 05:20:42 PM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-29T17:20:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X5.8941Y-5.5892
X6.085Y-5.5892
T2
X5.8823Y-5.7085
X6.0969Y-5.7085
T3
X4.325Y-2.2713
X4.325Y-5.15
X7.625Y-2.2713
X7.625Y-5.15
T0
M30
